
--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer_behavior.customer
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount 
FROM customer_behavior.customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) from customer_behavior.customer)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
FROM customer_behavior.customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
limit 5;


--Q4. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM  customer_behavior.customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


--Q5. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_behavior.customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q6. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior.customer
GROUP BY age_group
ORDER BY total_revenue desc;


--Q.7 What factors influence repeat purchases?
SELECT 
    subscription_status,
    discount_applied,
    promo_code_used,
    ROUND(AVG(previous_purchases),2) AS avg_repeat_purchases,
    COUNT(*) AS total_customers
FROM customer_behavior.customer
GROUP BY 
   subscription_status,
    discount_applied,
    promo_code_used
ORDER BY avg_repeat_purchases DESC;


--Q.8 Are high ratings associated with higher spending?
SELECT 
    ROUND(review_rating::numeric, 0) AS rating_bucket,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(AVG(previous_purchases),0) AS avg_loyalty
FROM customer_behavior.customer
WHERE review_rating IS NOT NULL
GROUP BY rating_bucket
ORDER BY rating_bucket DESC;



--Q.9 Do customers change behaviour across seasons?
SELECT 
    season,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(AVG(previous_purchases),0) AS avg_loyalty,
    COUNT(*) AS total_orders
FROM customer_behavior.customer
GROUP BY season
ORDER BY avg_spend DESC;


--Q.10 What behavioral differences exist between subscription vs non-subscription customers?
SELECT 
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(AVG(previous_purchases),0) AS avg_repeat_behavior,
    ROUND(AVG(review_rating::numeric),2) AS avg_satisfaction
FROM customer_behavior.customer
GROUP BY subscription_status;


--Q.11 Can we segment customers based on behavioral patterns?
SELECT 
    CASE 
        WHEN previous_purchases >= 20 THEN 'Highly Loyal'
        WHEN previous_purchases BETWEEN 10 AND 19 THEN 'Moderately Loyal'
        ELSE 'Low Engagement'
    END AS customer_segment,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(AVG(review_rating::numeric),0) AS avg_rating
FROM customer_behavior.customer
GROUP BY customer_segment
ORDER BY avg_spend DESC;


--Q.12 Do promo codes create long-term customers or one-time buyers?
SELECT 
    promo_code_used,
    COUNT(*) AS total_orders,
    ROUND(AVG(previous_purchases),0) AS avg_repeat_purchases,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(AVG(review_rating:: numeric),2) AS avg_rating
FROM customer_behavior.customer
GROUP BY promo_code_used;


--Q.13 Which product categories build the most loyal customers?
SELECT 
    category,
    COUNT(*) AS total_orders,
    ROUND(AVG(previous_purchases),0) AS avg_loyalty_score,
    ROUND(AVG(review_rating::numeric),2) AS avg_satisfaction
FROM customer_behavior.customer
GROUP BY category
ORDER BY avg_loyalty_score DESC;


--Q.14 Does payment preference reflect customer maturity?
SELECT 
    payment_method,
    ROUND(AVG(age),0) AS avg_customer_age,
    ROUND(AVG(previous_purchases),0) AS avg_loyalty,
    ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer_behavior.customer
GROUP BY payment_method
ORDER BY 2 DESC;


--Q.15 Are high-spending customers also highly engaged?
SELECT 
    CASE 
        WHEN purchase_amount >= 50000 THEN 'High Spender'
        WHEN purchase_amount BETWEEN 20000 AND 49999 THEN 'Medium Spender'
        ELSE 'Low Spender'
    END AS spending_group,
    COUNT(*) AS total_customers,
    ROUND(AVG(previous_purchases),0) AS avg_loyalty,
    ROUND(AVG(review_rating::numeric),2) AS avg_satisfaction
FROM customer_behavior.customer
GROUP BY spending_group
ORDER BY total_customers DESC;


--Q.16 Does purchase frequency align with actual engagement?
SELECT 
    frequency_of_purchases,
    COUNT(*) AS total_customers,
    ROUND(AVG(previous_purchases),0) AS avg_actual_repeat,
    ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer_behavior.customer
GROUP BY frequency_of_purchases
ORDER BY avg_spend DESC;






























